# Generated by Django 5.2.5 on 2025-08-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
